# Generated by Django 5.1.1 on 2025-03-02 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='ordered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='shipments', to=settings.AUTH_USER_MODEL, verbose_name='Ordered_by'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='shipments', to='products.product', verbose_name='Product'),
        ),
    ]
