# Generated by Django 5.1.1 on 2025-03-12 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='ordered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='shipments', to=settings.AUTH_USER_MODEL, verbose_name='Ordered_by'),
        ),
        migrations.AddField(
            model_name='shipmentcontents',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='shipment_contents', to='products.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='shipmentcontents',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_contents', to='products.shipment', verbose_name='Shipment'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.supplier', verbose_name='Supplier'),
        ),
    ]
