# Generated by Django 5.1.1 on 2025-03-04 18:11

import config.common.paths
import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='picture',
            field=imagekit.models.fields.ProcessedImageField(blank=True, max_length=512, null=True, upload_to=config.common.paths._default_media_path, verbose_name='Picture'),
        ),
    ]
