# Generated by Django 5.1.1 on 2025-03-15 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentcontents',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_contents', to='products.product', verbose_name='Product'),
        ),
    ]
