# Generated by Django 5.1.1 on 2025-03-21 18:09

import django.core.validators
import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_shipmentcontents_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeparturePoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Name')),
                ('address', models.CharField(max_length=240, verbose_name='Address')),
            ],
            options={
                'verbose_name': 'Write off',
                'verbose_name_plural': 'Write offs',
            },
        ),
        migrations.CreateModel(
            name='WriteOff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000000)], verbose_name='Quantity')),
                ('departure_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='write_offs', to='products.departurepoint', verbose_name='Departure point')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='write_offs', to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Write off',
                'verbose_name_plural': 'Write offs',
            },
        ),
    ]
