# Generated by Django 5.1.1 on 2025-03-08 17:41

import django.core.validators
import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='product',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='quantity',
        ),
        migrations.CreateModel(
            name='ShipmentContents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000000)], verbose_name='Quantity')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='shipments', to='products.product', verbose_name='Product')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_contents', to='products.shipment', verbose_name='Shipment')),
            ],
            options={
                'verbose_name': 'Shipment contents',
                'verbose_name_plural': 'Shipments contents',
            },
        ),
    ]
