# Generated by Django 5.1.1 on 2025-03-21 19:32

import django.core.validators
import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_departurepoint_writeoff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writeoff',
            name='product',
        ),
        migrations.RemoveField(
            model_name='writeoff',
            name='quantity',
        ),
        migrations.AddField(
            model_name='writeoff',
            name='is_manual',
            field=models.BooleanField(default=True, help_text='Indicates the way write off created, by manager or api', verbose_name='Is manual'),
        ),
        migrations.CreateModel(
            name='WriteOffContents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000000)], verbose_name='Quantity')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='write_off_contents', to='products.product', verbose_name='Product')),
                ('write_off', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='write_off_contents', to='products.writeoff', verbose_name='Write off')),
            ],
            options={
                'verbose_name': 'Write off contents',
                'verbose_name_plural': 'Write off contents',
            },
        ),
    ]
