# Generated by Django 5.1.1 on 2025-03-10 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_shipment_product_remove_shipment_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.supplier', verbose_name='Supplier'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('In assembly', 'In assembly'), ('In delivery', 'In delivery'), ('Being unloaded', 'Being unloaded'), ('Under review', 'Under review'), ('Accepted', 'Accepted')], default='In assembly', max_length=16, verbose_name='Status'),
        ),
    ]
