# Generated by Django 5.1.1 on 2025-03-22 16:14

import django.core.validators
import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('products', '0005_remove_writeoff_product_remove_writeoff_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writeoffcontents',
            name='product',
        ),
        migrations.RemoveField(
            model_name='writeoffcontents',
            name='write_off',
        ),
        migrations.CreateModel(
            name='ProductActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('object_id', models.PositiveIntegerField(verbose_name='Object ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000000)], verbose_name='Quantity')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_activities', to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product activity',
                'verbose_name_plural': 'Product activities',
            },
        ),
        migrations.DeleteModel(
            name='ShipmentContents',
        ),
        migrations.DeleteModel(
            name='WriteOffContents',
        ),
    ]
