# Generated by Django 5.1.1 on 2025-03-30 11:29

from django.contrib.postgres.operations import CreateExtension
import django.contrib.gis.db.models.fields
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_writeoffcontents_product_and_more'),
    ]

    operations = [
        CreateExtension("postgis"),
        migrations.AlterModelOptions(
            name='departurepoint',
            options={'verbose_name': 'Departure point', 'verbose_name_plural': 'Departure points'},
        ),
        migrations.AddField(
            model_name='departurepoint',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='Coordinates'),
        ),
    ]
