# Generated by Django 5.1.1 on 2025-03-30 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_departurepoint_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departurepoint',
            name='address',
        ),
    ]
