# Generated by Django 5.1.1 on 2025-04-10 05:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_departurepoint_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='to_notify',
            field=models.BooleanField(default=False, help_text='Indicates the need for notification when the quantity on storage beyond than minimal', verbose_name='To notify'),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_quantity',
            field=models.IntegerField(blank=True, default=15, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000000)], verbose_name='Minimal quantity'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=120, unique=True, verbose_name='Sku'),
        ),
    ]
