# Generated by Django 5.1.1 on 2025-04-12 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_to_notify_alter_product_min_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writeoff',
            name='departure_point',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='write_offs', to='products.departurepoint', verbose_name='Departure point'),
        ),
    ]
