# Generated by Django 5.1.1 on 2025-04-18 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_writeoff_departure_point'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
