# Generated by Django 5.1.1 on 2025-05-01 14:08

import django_measurement.models
import measurement.measures.mass
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_delete_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=django_measurement.models.MeasurementField(help_text='Weight of one unit of product in packaging', measurement=measurement.measures.mass.Mass, null=True, verbose_name='Weight'),
        ),
    ]
