# Generated by Django 5.1.1 on 2025-05-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='departurepoint',
            name='type',
            field=models.CharField(choices=[('Not specified', 'Not specified'), ('In delivery', 'In delivery'), ('In assembly', 'In assembly'), ('Being unloaded', 'Being unloaded')], default='Not specified', max_length=20, verbose_name='Type'),
        ),
    ]
