# Generated by Django 5.1.1 on 2025-05-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_departurepoint_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departurepoint',
            name='type',
            field=models.CharField(choices=[('Not specified', 'Not specified'), ('Retail place', 'Retail place'), ('Supplier storage', 'Supplier storage'), ('Other storage', 'Other storage')], default='Not specified', max_length=20, verbose_name='Type'),
        ),
    ]
