# Generated by Django 5.1.1 on 2025-05-27 17:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_departurepoint_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='followers',
            field=models.ManyToManyField(blank=True, help_text='Notifying users that followed, for status changes', related_name='followed_shipments', to=settings.AUTH_USER_MODEL, verbose_name='Followers'),
        ),
    ]
