# Generated by Django 5.1.1 on 2025-05-28 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_shipment_followers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
