# Generated by Django 5.1.1 on 2025-06-24 17:39

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_delete_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Name')),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='Coordinates')),
            ],
            options={
                'verbose_name': 'Storage',
                'verbose_name_plural': 'Storages',
            },
        ),
        migrations.AlterField(
            model_name='shipment',
            name='ordered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='shipments', to=settings.AUTH_USER_MODEL, verbose_name='Ordered by'),
        ),
    ]
