# Generated by Django 5.1.1 on 2025-05-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_departurepoint_type'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followed_shipments',
            field=models.ManyToManyField(blank=True, help_text='Notifying user for status changes of followed shipments', related_name='users', to='products.shipment', verbose_name='Followed shipments'),
        ),
    ]
