# Generated by Django 5.1.1 on 2025-05-27 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_followed_shipments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followed_shipments',
        ),
    ]
