from django.urls import path

from .views import (
    CategoryCreateView,
    CategoryUpdateView,
    CategoryDeleteView,
    ProductCreateView,
    ProductListView,
    ProductDetailView,
    ProductUpdateView,
    ProductDeleteView,
    SupplierCreateView,
    SupplierListView,
    SupplierUpdateView,
    SupplierDeleteView,
    ShipmentCreateView,
    ShipmentListView,
    ShipmentDetailView,
    ShipmentUpdateView,
    ShipmentDeleteView,
    WriteOffListView,
    WriteOffCreateView,
    WriteOffDetailView,
    WriteOffDeleteView,
    DeparturePointCreateView,
    DeparturePointListView,
    DeparturePointUpdateView,
    ProductActivityDeleteView,
    ProductActivityUpdateView,
    DeparturePointDeleteView,
)

app_name = "products"

urlpatterns = [
    path(
        "categories/create/",
        CategoryCreateView.as_view(),
        name="create_category",
    ),
    path(
        "categories/<int:pk>/update/",
        CategoryUpdateView.as_view(),
        name="update_category",
    ),
    path(
        "categories/<int:pk>/delete/",
        CategoryDeleteView.as_view(),
        name="delete_category",
    ),
    path(
        "",
        ProductListView.as_view(),
        name="list_products",
    ),
    path(
        "create/",
        ProductCreateView.as_view(),
        name="create_product",
    ),
    path(
        "<int:pk>/detail/",
        ProductDetailView.as_view(),
        name="detail_product",
    ),
    path(
        "<int:pk>/update/",
        ProductUpdateView.as_view(),
        name="update_product",
    ),
    path(
        "<int:pk>/delete/",
        ProductDeleteView.as_view(),
        name="delete_product",
    ),
    path(
        "suppliers/",
        SupplierListView.as_view(),
        name="list_suppliers",
    ),
    path(
        "suppliers/create/",
        SupplierCreateView.as_view(),
        name="create_supplier",
    ),
    path(
        "suppliers/<int:pk>/update/",
        SupplierUpdateView.as_view(),
        name="update_supplier",
    ),
    path(
        "suppliers/<int:pk>/delete/",
        SupplierDeleteView.as_view(),
        name="delete_supplier",
    ),
    path(
        "shipments/create/",
        ShipmentCreateView.as_view(),
        name="create_shipment",
    ),
    path(
        "shipments/",
        ShipmentListView.as_view(),
        name="list_shipments",
    ),
    path(
        "shipments/<int:pk>/detail/",
        ShipmentDetailView.as_view(),
        name="detail_shipment",
    ),
    path(
        "shipments/<int:pk>/update/",
        ShipmentUpdateView.as_view(),
        name="update_shipment",
    ),
    path(
        "shipments/<int:pk>/delete/",
        ShipmentDeleteView.as_view(),
        name="delete_shipment",
    ),
    path(
        "product-activity/<int:pk>/update/",
        ProductActivityUpdateView.as_view(),
        name="update_product_activity",
    ),
    path(
        "product-activity/<int:pk>/delete/",
        ProductActivityDeleteView.as_view(),
        name="delete_product_activity",
    ),
    path(
        "write-offs/",
        WriteOffListView.as_view(),
        name="list_write_offs",
    ),
    path(
        "write-offs/create/",
        WriteOffCreateView.as_view(),
        name="create_write_off",
    ),
    path(
        "write-offs/<int:pk>/detail/",
        WriteOffDetailView.as_view(),
        name="detail_write_off",
    ),
    path(
        "write-offs/<int:pk>/delete/",
        WriteOffDeleteView.as_view(),
        name="delete_write_off",
    ),
    path(
        "departure-points/create/",
        DeparturePointCreateView.as_view(),
        name="create_departure_point",
    ),
    path(
        "departure-points/",
        DeparturePointListView.as_view(),
        name="list_departure_points",
    ),
    path(
        "departure-points/<int:pk>/update/",
        DeparturePointUpdateView.as_view(),
        name="update_departure_point",
    ),
    path(
        "departure-points/<int:pk>/delete/",
        DeparturePointDeleteView.as_view(),
        name="delete_departure_point",
    )
]
